name: simile-example
channels:
  - rdkit
  - bioconda
  - defaults
dependencies:
  - sortedcollections
  - numpy
  - pandas
  - scipy
  - seaborn
  - jupyter
  - matplotlib
  - python=3.7
  - rdkit
  - matchms
  - networkx
